# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sax-machine}
  s.version = "0.0.18"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Dix", "Ryan Lovelett"]
  s.date = %q{2011-06-26}
  s.description = %q{A declarative sax parsing library backed by Nokogiri.}
  s.email = ["paul@pauldix.net", "ryan@wahvee.com"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/sax-machine.rb",
    "lib/sax-machine/sax_collection_config.rb",
    "lib/sax-machine/sax_config.rb",
    "lib/sax-machine/sax_document.rb",
    "lib/sax-machine/sax_element_config.rb",
    "lib/sax-machine/sax_handler.rb",
    "sax-machine.gemspec",
    "spec/benchmarks/amazon.xml",
    "spec/benchmarks/benchmark.rb",
    "spec/benchmarks/public_timeline.xml",
    "spec/sax-machine/atom.xml",
    "spec/sax-machine/include_sax_machine_spec.rb",
    "spec/sax-machine/sax_document_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/RLovelett/sax-machine}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A declarative sax parsing library backed by Nokogiri.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.6.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, ["~> 0.9.9"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.4.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.6.1"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, ["~> 0.9.9"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.4.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.6.1"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, ["~> 0.9.9"])
  end
end

